version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    env_file:
      - .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - network1
networks:
  network1:
    name: network1